export const sampleJobs = [
  {
    id: 'job-001',
    title: '病棟看護師（正社員）',
    department: '外科病棟',
    employmentType: '正社員',
    salary: '月給28万〜35万円（経験年数による）',
    workHours: '日勤 8:30-17:30 / 夜勤 16:30-翌9:00（二交代制）',
    requirements: '看護師免許必須、病棟経験3年以上',
    preferred: '外科病棟経験、急性期経験',
    benefits: '住宅手当、夜勤手当、賞与年2回（4.2ヶ月）、退職金制度、院内保育所、車通勤可',
    description: '801床の急性期病院で、外科病棟の看護業務全般をお任せします。電子カルテ導入済み。教育体制が充実しており、ブランクのある方も歓迎です。',
    appealPoints: '残業月平均10時間以下、有給取得率80%以上、ママナース多数在籍',
    headcount: 2,
    urgency: 'high',
    status: 'active',
    agencies: ['マイナビ看護師', 'ナース人材バンク', 'レバウェル看護'],
    createdAt: '2026-06-10',
    updatedAt: '2026-06-20',
  },
  {
    id: 'job-002',
    title: '訪問看護師（正社員）',
    department: '訪問看護ステーション',
    employmentType: '正社員',
    salary: '月給30万〜38万円',
    workHours: '9:00-18:00（オンコール月4-5回）',
    requirements: '看護師免許必須、臨床経験3年以上',
    preferred: '訪問看護経験、在宅医療経験',
    benefits: '車両貸与、直行直帰可、賞与年2回、退職金制度',
    description: '在宅療養中の患者様への訪問看護業務。1日4-5件の訪問。多職種連携チームでのカンファレンスあり。',
    appealPoints: '直行直帰OK、残業ほぼなし、未経験者には同行研修3ヶ月',
    headcount: 3,
    urgency: 'medium',
    status: 'active',
    agencies: ['マイナビ看護師', 'ナース人材バンク'],
    createdAt: '2026-06-15',
    updatedAt: '2026-06-22',
  },
  {
    id: 'job-003',
    title: '理学療法士（正社員）',
    department: 'リハビリテーション科',
    employmentType: '正社員',
    salary: '月給25万〜32万円',
    workHours: '8:30-17:30（日勤のみ）',
    requirements: '理学療法士免許必須',
    preferred: '急性期リハビリ経験、回復期リハビリ経験',
    benefits: '賞与年2回（3.8ヶ月）、退職金制度、学会参加費補助',
    description: '急性期から回復期まで幅広いリハビリテーションを担当。整形外科・脳外科の術後リハビリが中心。',
    appealPoints: '症例数が豊富、専門資格取得支援制度あり',
    headcount: 1,
    urgency: 'low',
    status: 'draft',
    agencies: [],
    createdAt: '2026-06-18',
    updatedAt: '2026-06-18',
  },
];

export const sampleAgencies = [
  { id: 'ag-001', name: 'マイナビ看護師', contact: '田中太郎', email: 'tanaka@mynavi-kaigo.example.com', phone: '03-1234-5678' },
  { id: 'ag-002', name: 'ナース人材バンク', contact: '鈴木花子', email: 'suzuki@nhb.example.com', phone: '03-2345-6789' },
  { id: 'ag-003', name: 'レバウェル看護', contact: '佐藤一郎', email: 'sato@leverages.example.com', phone: '03-3456-7890' },
  { id: 'ag-004', name: 'ナースではたらこ', contact: '山田美咲', email: 'yamada@dip.example.com', phone: '03-4567-8901' },
  { id: 'ag-005', name: 'MCナースネット', contact: '高橋健', email: 'takahashi@mc-nurse.example.com', phone: '03-5678-9012' },
];

export const sampleCandidates = [
  {
    id: 'cand-001',
    name: '山本 真由美',
    jobId: 'job-001',
    agencyId: 'ag-001',
    source: 'agency',
    status: 'interview_scheduled',
    appliedAt: '2026-06-12',
    experience: '外科病棟5年（急性期300床）',
    hasResume: true,
    aiAnalysis: {
      matchScore: 82,
      summary: '外科病棟5年の経験あり。急性期300床での実務経験が求人要件と合致。夜勤経験も豊富で即戦力として期待できる。',
      strengths: ['外科病棟5年の即戦力', '急性期300床での経験', '電子カルテ操作に慣れている'],
      concerns: ['転職理由の確認が必要（短期離職の懸念）'],
      interviewPoints: ['前職の退職理由と今後のキャリアプラン', '夜勤頻度の希望（二交代制への対応可否）', 'プリセプター経験の有無'],
    },
    statusHistory: [
      { status: 'applied', date: '2026-06-12', note: 'マイナビ看護師経由で推薦' },
      { status: 'document_passed', date: '2026-06-13', note: '書類通過' },
      { status: 'interview_scheduled', date: '2026-06-15', note: '6/20 14:00 面接設定' },
    ],
  },
  {
    id: 'cand-002',
    name: '田中 さくら',
    jobId: 'job-001',
    agencyId: 'ag-002',
    source: 'agency',
    status: 'offered',
    appliedAt: '2026-06-10',
    experience: '外科・ICU計7年',
    hasResume: true,
    aiAnalysis: {
      matchScore: 94,
      summary: '外科病棟とICUで計7年の豊富な経験。急性期看護のスペシャリスト。リーダー経験もあり、即戦力かつチームへの貢献が期待できる。',
      strengths: ['外科+ICU計7年の豊富な臨床経験', 'リーダー・プリセプター経験あり', '認定看護師取得に向けて学習中'],
      concerns: ['給与面の期待値がやや高い可能性'],
      interviewPoints: ['希望年収と現年収の確認', '認定看護師取得への支援希望の有無', 'ICUから病棟への異動に対する考え'],
    },
    statusHistory: [
      { status: 'applied', date: '2026-06-10', note: 'ナース人材バンク経由で推薦' },
      { status: 'document_passed', date: '2026-06-10', note: '即日書類通過' },
      { status: 'interview_completed', date: '2026-06-14', note: '面接実施、評価◎' },
      { status: 'offered', date: '2026-06-14', note: '当日内定提示' },
    ],
  },
  {
    id: 'cand-003',
    name: '佐々木 健一',
    jobId: 'job-002',
    agencyId: 'ag-001',
    source: 'agency',
    status: 'applied',
    appliedAt: '2026-06-20',
    experience: '急性期病棟4年、訪問看護1年',
    hasResume: true,
    aiAnalysis: {
      matchScore: 71,
      summary: '急性期病棟4年の基盤に加え訪問看護1年の経験あり。訪問看護の実務経験があるが期間が短い。在宅医療への適性は確認が必要。',
      strengths: ['急性期の臨床経験が基盤にある', '訪問看護の実務経験あり', '多職種連携の経験'],
      concerns: ['訪問看護経験が1年と短い', 'オンコール対応への耐性が未知数'],
      interviewPoints: ['訪問看護を続けたい理由', 'オンコール対応の経験と許容範囲', '運転免許の有無と訪問エリアの希望'],
    },
    statusHistory: [
      { status: 'applied', date: '2026-06-20', note: 'マイナビ看護師経由' },
    ],
  },
  {
    id: 'cand-004',
    name: '高橋 ゆき',
    jobId: 'job-001',
    agencyId: 'ag-003',
    source: 'agency',
    status: 'ng',
    appliedAt: '2026-06-08',
    experience: '内科病棟3年',
    hasResume: true,
    aiAnalysis: {
      matchScore: 38,
      summary: '内科病棟3年の経験だが、求人が求める外科経験がない。基本的な看護スキルは備えているが、外科病棟での即戦力としては難しい。',
      strengths: ['看護基礎スキルは問題なし', '患者対応の評判が良い'],
      concerns: ['外科経験がゼロ', '臨床年数が要件の3年ギリギリ'],
      interviewPoints: [],
    },
    ngReason: {
      category: 'experience_mismatch',
      detail: '外科経験なし',
      feedbackSent: true,
    },
    statusHistory: [
      { status: 'applied', date: '2026-06-08', note: 'レバウェル看護経由' },
      { status: 'interview_completed', date: '2026-06-12', note: '面接実施' },
      { status: 'ng', date: '2026-06-12', note: '面接NG: 外科経験なし、基本スキルは問題ないが即戦力としては難しい' },
    ],
  },
  {
    id: 'cand-005',
    name: '中村 あおい',
    jobId: 'job-001',
    source: 'media',
    mediaId: 'media-002',
    status: 'document_passed',
    appliedAt: '2026-06-22',
    experience: '外科病棟3年、手術室2年',
    hasResume: true,
    aiAnalysis: {
      matchScore: 88,
      summary: '外科病棟3年に加え手術室2年の経験。オペ前後の患者管理に精通しており、外科病棟での即戦力として高く評価できる。',
      strengths: ['外科+手術室で計5年の専門経験', '術前術後管理のスキル', '急性期での実績'],
      concerns: ['前職の退職から3ヶ月のブランクあり'],
      interviewPoints: ['ブランク期間の過ごし方', '手術室から病棟へ戻る理由', '夜勤シフトへの対応可否'],
    },
    statusHistory: [
      { status: 'applied', date: '2026-06-22', note: 'ジョブメドレー経由で応募' },
      { status: 'document_passed', date: '2026-06-23', note: 'AI分析スコア88点、書類通過' },
    ],
  },
];

export const ngReasonCategories = [
  {
    id: 'experience_mismatch',
    label: '経験・スキル不足',
    subcategories: ['必要な診療科経験なし', '臨床年数不足', '必要な資格なし', 'スキルレベル不足'],
  },
  {
    id: 'culture_fit',
    label: '組織風土とのミスマッチ',
    subcategories: ['コミュニケーションスタイル', 'チームワーク志向の違い', '働き方の価値観'],
  },
  {
    id: 'conditions_mismatch',
    label: '条件面の不一致',
    subcategories: ['給与希望が合わない', '勤務形態が合わない', '通勤距離', '入職時期が合わない'],
  },
  {
    id: 'motivation',
    label: '志望動機・意欲',
    subcategories: ['志望理由が不明確', '長期就業の意思が不明', '他院優先の印象'],
  },
  {
    id: 'other_decided',
    label: '他院で決定',
    subcategories: ['候補者辞退（他院内定）', '候補者辞退（現職残留）', '候補者辞退（その他）'],
  },
  {
    id: 'other',
    label: 'その他',
    subcategories: ['面接無断欠席', '連絡不通', 'その他'],
  },
];

export const sampleMediaPlatforms = [
  { id: 'media-001', name: 'Indeed', type: '総合求人', status: 'active', postings: 2, applicants: 8, monthlyCost: '¥48,000', costModel: 'クリック課金', url: 'indeed.com', apiAvailable: true },
  { id: 'media-002', name: 'ジョブメドレー', type: '医療特化', status: 'active', postings: 2, applicants: 5, monthlyCost: '¥0（成功報酬）', costModel: '成功報酬', url: 'jobmedley.com', apiAvailable: true },
  { id: 'media-003', name: 'コメディカルドットコム', type: '医療特化', status: 'active', postings: 1, applicants: 3, monthlyCost: '¥0（成功報酬）', costModel: '成功報酬', url: 'comedical.com', apiAvailable: false },
  { id: 'media-004', name: 'グッピー', type: '医療特化', status: 'paused', postings: 0, applicants: 1, monthlyCost: '¥33,000', costModel: '月額固定', url: 'guppy.jp', apiAvailable: false },
  { id: 'media-005', name: 'ハローワーク', type: '公共', status: 'active', postings: 3, applicants: 2, monthlyCost: '無料', costModel: '無料', url: 'hellowork.mhlw.go.jp', apiAvailable: false },
];

export const candidateStatuses = {
  applied: { label: '推薦受付', color: '#6b7280', bg: '#f3f4f6' },
  document_passed: { label: '書類通過', color: '#2563eb', bg: '#eff6ff' },
  interview_scheduled: { label: '面接予定', color: '#7c3aed', bg: '#f5f3ff' },
  interview_completed: { label: '面接済', color: '#0891b2', bg: '#ecfeff' },
  offered: { label: '内定', color: '#059669', bg: '#ecfdf5' },
  accepted: { label: '内定承諾', color: '#047857', bg: '#d1fae5' },
  joined: { label: '入職', color: '#065f46', bg: '#a7f3d0' },
  ng: { label: 'NG', color: '#dc2626', bg: '#fef2f2' },
  withdrawn: { label: '辞退', color: '#9ca3af', bg: '#f9fafb' },
};
